### ISSUE TITLE
sppmon.py fails when trying to create sppmon database, but doc says to create that beforehand.

### ISSUE THREAD

**Issue by SupremeGit** [IBM/spectrum-protect-sppmon#55] opened 2021-04-23 05:37 UTC
I followed instructions, so the sppmon database already exists, and sppmonInfluxUser IS authorised to use that database.

The DB does not need to be created, so of course, when sppmon.py tries to create it, it fails, because sppmonInfluxUser does not have admin privilege, nor should it:

Starting SPPMon
Setting up configurations
Exception in FILE: influx_client.py, Line: 132, Exception: <class 'influxdb.exceptions.InfluxDBClientError'>
Exception Message: 403: {"error":"error authorizing query: sppmonInfluxUser not authorized to execute statement 'CREATE DATABASE sppmon', requires admin privilege"}
Exception in FILE: sppmon.py, Line: 426, Exception: <class 'ValueError'>
Exception Message: Login into influxdb failed
error while setting up critical config. Aborting
Storing script metrics
Exception in FILE: sppmon.py, Line: 610, Exception: <class 'ValueError'>
Exception Message: no influxClient set up
Error when storing sppmon-metrics, skipping this step. Possible insert-buffer data loss
Error occured while executing sppmon
check log for details: grep "PID 154451" /home/sppmon/sppmonLogs/sppconnections_audccfosppm1.log > sppmon.log.154451

**Comment by SupremeGit** [comment] 2021-04-23 07:14
As a temporary workaround, i put the influx admin user details into the config, so that had perms to create db.

The sppmon.py then went ahead and did a great job of collecting lots of info, so dashboards are full of data.

So things appear to be working very well (great job devs!), but there are a just a couple of other small issues!:

1) some of the graphs have crazy numbers, eg:
Last maintenance shows "1618873864429"
Last hypervisor inventory shows "1618855335000"
What on earth are those numbers meant to be?
etc

Housekeeping Job duration for Hypervisor Inventory: 135123
Housekeeping Job duration for Maintenance: 664931
Housekeeping Job duration for Storage server inventory: 458538
What are these nonsense numbers, they cant be seconds!

Additional Statistics (last 24H)  (VM Replicated) shows: 1831874615714
Additional Statistics (last 24H) (VM Transferred) shows: 4515300592857
Those numbers could be number of bytes - ie 1.8 TB & 4.5 TB , but who knows. And if they are, those are still utterly useless meaningless numbers to any human being - they need to be converted to MB,GB,TB etc, so people can understand them, without having to count the number of digits...

2) the --all job produced errors like this:
>> executing ssh commands, which are labled to be executed for VSNAP ssh clients
Exception in FILE: methods_utils.py, Line: 91, Exception: <class 'ValueError'>
Exception Message: the mpstat values are not in the expected pattern
Exception args: (['Linux 4.19.133-1c.el7.x86_64 (myhostname) \t23/04/21 \t_x86_64_\t(40 CPU)', '', '16:16:54     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle', '16:16:54     all    0.68    0.00    3.69    1.92    0.00    0.16    0.00    0.00    0.00   93.54'], <sppConnection.ssh_client.SshCommand object at 0x7f8dfc306c70>, <SshTypes.VSNAP: 'VSNAP'>)
Error when parsing result, skipping parsing of this result

**Comment by NielsKorschinsky** [comment] 2021-04-25 18:08
Hello @SupremeGit ,

You're observations are correct, the influxd-user currently needs admin privileges, there is no way arround these permissions for now. I'm aware of this issue but have no direct solution for now.
Since the user also creates/alters continuous queries and retention policies and requires admin to do so, the best way is to just give him the admin role as you did.

Thanks for you feedback! It's gread to hear that SPPMon is useful for you.


1. These numbers are epoch-timestamps. In my version of the dashboard these have the type `Unit->Date&Time->From Now`.
This should convert it to a `2 hours ago`-Style. 
Be aware threshholds dont work with `from now` (coloring dependend on >1 day / 1 week a.o).

I do not know why this isn't set for you, either try to re-import the dashboard or change the unit by yourself within the tab `field`
![grafik](https://user-images.githubusercontent.com/49568673/116004075-61262500-a601-11eb-8e70-2e146f27e557.png)


2. It seems like your system has a different mpStat output than our supported machine. These ssh-commands are quite fragile in terms of formatting. Do you have any special settings/formatting on your system? 
Could you please post the cmd output if you execute `mpstat` on your machine on that certain host via ssh?

This should not stop all of sppmons capturing, only prevent the data of mpstat for that certain system to be saved. You may use all other features regulary.

**Comment by SupremeGit** [comment] 2021-04-26 08:53
Ty Niel, for all your dev work on this, and for tips re the units.

I found this in the json for Last Hypervisor Inventory: "unit": "dateTimeFromNow"
So looks like date format is already set to "FromNow" in my dashboard, but it is not working - most likely because my Grafana is a bit old, I did not get it from git. I was lazy & installed the latest version available from standard Red Hat 8 appstream repos, so i have grafana-6.7.4-3.el8.x86_64
I will install newer Grafana from git, and see how i go with that.

Re mpstat, this is what i get:

ssh -i /home/meh/foo/blah sppmon@meh mpstat
"Linux 4.19.133-1c.el7.x86_64 (meh.blah.foo.com)         04/26/2021      _x86_64_        (40 CPU)

06:07:11 PM  CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
06:07:11 PM  all    0.69    0.00    3.72    2.26    0.00    0.16    0.00    0.00    0.00   93.18"

Note! the date there is 04/26/2021 -  ie mm/dd 

which is really odd, because in the error logs i got:
      Exception args: (['Linux 4.19.133-1c.el7.x86_64 (myhostname) \t23/04/21 \t_x86_64_\t(40 CPU)'

ie the date in error logs is dd/mm....  

So maybe that is the issue, if your script expects mm/dd. 
I can't quite see how mpstat gave dd/mm in the logs though, as it is giving me mm/dd now when i run it as sppmon user Perhaps sppmon.py was sshing in and somehow getting a different locale.

Will have more of a look into this tomorrow, but difference in date format due to locale looks likely culprtit here!

**Comment by NielsKorschinsky** [comment] 2021-04-26 10:29
Hello @SupremeGit ,

I did some testing and found the bug. The problem is actually not the localized date format, but the year. 
This regex did fail due the date format `23/04/21` instead of my expected `23/04/2021`.
I did change this now to make it a bit more flexible. 

The changes are pushed into my next bugfix branch, though if you want to use it asap you may replace one line for yourself.
To do so, open the file `python/sppmonMethods/ssh.py` and replace line 458:

From:
```python
        pattern = re.compile(r"(.*)\s+\((.*)\)\s+(\d{2}\/\d{2}\/\d{4})\s+(\S*)\s+\((\d+)\sCPU\)")
```
to ->
```python
        pattern = re.compile((.*)\s+\((.*)\)\s+(\d{2}\/\d{2}\/(?:\d{4}|\d{2}))\s+(\S*)\s+\((\d+)\sCPU\))
 ```` 
 Please make sure to maintain the indend of the line, in case just replace everything behind the `=`.
 
 If everything goes as expected, it should run fine now!

**Comment by SupremeGit** [comment] 2021-04-27 02:12
Aah tyvm Niels.

I've edited the regex as you suggest and that has fixed the mpstat parsing errors.

I also upgraded my old red hat grafana to the latest grafana in the repo (grafana-7.5.4-1.x86_64) - grafana service did not start after the upgrade, but journal showed it was just looking for /etc/grafana/grafana.ini, which did not exist so i created an empty one, and new grafana started.

Now, with new grafana, i have proper FromNow dates, and, it also fixed the other large numbers, converting them into TB, and so on. 

So, looks like all the issues I found are now fixed.

Thank you for fixing that regex, and, I apologise for not following your instructions to install new grafana from the grafana repository!

 Please feel free to close this bugreport!

**Comment by NielsKorschinsky** [comment] 2021-04-27 08:39
Great to hear that! You're welcome. If you have any further issues or notice anything which should be fixed for everyone, feel free to open up another issue!

**Closed by NielsKorschinsky** 2021-04-27 08:39 UTC
Labels: user support

**Comment by SupremeGit** [comment] 2021-04-28 05:55
Oh, just one note, turns out the fixedregular expression as given did not quite work.

It got rid of the stdout showing mpstat parsing errors, and i thought it fixed the issue - but actually the entire script was failing due to syntax error. 

To get it workign properly I needed to enclose in r"", for raw notation, like the original regex was, ie:
        pattern = re.compile(r"(.*)\s+\((.*)\)\s+(\d{2}\/\d{2}\/(?:\d{4}|\d{2}))\s+(\S*)\s+\((\d+)\sCPU\)")

**Comment by NielsKorschinsky** [comment] 2021-04-28 08:34
Oh I'm sorry, that was a copy-paste error on my side. I'm glad you were able to fix it for yourself. I've edited my pot above.
Your pattern looks good to me.
